import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import { openDatabaseSync } from 'expo-sqlite';

// Generated by drizzle-kit; see drizzle/migrations.js
import migrations from '../drizzle/migrations';

const DATABASE_NAME = 'microphone_check.db';

export const expoDb = openDatabaseSync(DATABASE_NAME);
export const db = drizzle(expoDb);

/** Column names currently on a table (empty when the table does not exist). */
const getTableColumns = async (table: string): Promise<string[]> => {
  try {
    const rows = await expoDb.getAllAsync<{ name: string }>(`PRAGMA table_info(${table});`);
    return rows.map(r => r.name);
  } catch {
    return [];
  }
};

/**
 * One-off repairs for databases created before drizzle migrations existed.
 *
 * Versions up to 3.0 built their schema from hand-written SQL and never
 * recorded anything drizzle can recognise. Those databases predate the
 * migration journal, so the tracked migrations cannot express the change; this
 * runs first, is guarded by PRAGMA checks, and does nothing on a database that
 * is already current or brand new.
 */
const upgradePreMigrationDatabase = async () => {
  const noteColumns = await getTableColumns('notes');

  // The legacy notes table declared `date UNIQUE`, which capped a day at one
  // note. SQLite cannot drop a constraint in place, so the table is rebuilt
  // with the existing rows carried over and given generated ids.
  if (noteColumns.length > 0 && !noteColumns.includes('note_id')) {
    await expoDb.execAsync(`
      PRAGMA foreign_keys=off;
      BEGIN TRANSACTION;
      ALTER TABLE notes RENAME TO notes_pre_migration;
      CREATE TABLE notes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        note_id TEXT,
        date TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at INTEGER,
        updated_at INTEGER
      );
      INSERT INTO notes (note_id, date, content, created_at, updated_at)
        SELECT lower(hex(randomblob(8))), date, content, created_at, updated_at
        FROM notes_pre_migration
        WHERE content IS NOT NULL AND trim(content) != '';
      DROP TABLE notes_pre_migration;
      COMMIT;
      PRAGMA foreign_keys=on;
    `);
  }

  const eventColumns = await getTableColumns('events');
  if (eventColumns.length > 0 && !eventColumns.includes('completed')) {
    // Added nullable so an older database can never fail on existing rows.
    await expoDb.execAsync('ALTER TABLE events ADD COLUMN completed INTEGER DEFAULT 0;');
  }
};

export const initDb = async () => {
  await upgradePreMigrationDatabase();

  // Everything from here on is managed by drizzle-kit. The baseline migration
  // uses CREATE TABLE IF NOT EXISTS, so applying it to a database that already
  // holds the user's data is a no-op rather than an error.
  await migrate(db, migrations);

  await expoDb.execAsync(`
    CREATE INDEX IF NOT EXISTS idx_notes_date ON notes(date);
    CREATE INDEX IF NOT EXISTS idx_events_dates ON events(start_date, end_date);
  `);
};
